import Head from "next/head";
//styles
import styles from "../../styles/mangaSingle/MangaSingle.module.css";
//API
import { getMangaById } from "../../api/mangas";
import { getCategories } from "../../api/categories";
//components
import SideBar from "../../components/layout/SideBar/SideBar";
import { Box } from "@mui/material";
import { useRefreshState } from "../../store/useRefreshState";
import { useRouter } from "next/router";
import MangaInfo from "../../components/MangaSingle/MangaInfo";
import { Fragment, useEffect } from "react";
import MangaItemWithInfo from "../../components/UI/MangaList/MangaItemWIthInfo";
import RateManga from "../../components/RateManga/RateManga";

function MostPopular(props) {
  const router = useRouter();
  const { manga } = props;
  const { categories } = props;

  const [refreshState] = useRefreshState();

  useEffect(() => {
    router.events.on("routeChangeStart", refreshState);

    return () => {
      router.events.off("routeChangeStart", refreshState);
    };
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Manga Srbija | Naruto Manga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bgcolor={"background.default"} className="container">
        <SideBar categories={categories} />
        <main className={styles.main}>
          <MangaInfo manga={manga} styles={styles} />
          <Box sx={{display:'grid',gridTemplateColumns:'3fr 1fr',columnGap:'1em',alignItems:'stretch'}}>
            <MangaItemWithInfo manga={manga} styles={styles} />
             <RateManga />
          </Box>
        </main>
      </Box>
    </Fragment>
  );
}

export async function getStaticProps({ params }) {
  const categories = await getCategories();
  const manga = await getMangaById(params.id);

  return {
    props: {
      manga,
      categories,
    },
  };
}

export async function getStaticPaths() {
  const paths = [
    {
      params: { id: "1" },
      params: { id: "2" },
      params: { id: "3" },
      params: { id: "4" },
      params: { id: "5" },
      params: { id: "6" },
      params: { id: "7" },
      params: { id: "8" },
    },
  ];
  return {
    fallback: true,
    paths,
  };
}

export default MostPopular;
