import Head from "next/head";
//styles
import styles from "../../styles/popular-mangas/Popular.module.css";
//components
//API
import { getCategories } from "../../api/categories";
import { getByLetter, countMangas } from "../../api/mangas";
import AppPagination from "../../components/UI/AppPagination";
import { Fragment, useEffect, useState } from "react";
import Letters from "../../components/LetterList/Letters";
import { Box } from "@mui/system";
import MangaListItems from "../../components/MangaList/MangaList";
import SideBar from "../../components/layout/SideBar/SideBar";
import { useRouter } from "next/router";
import { useRefreshState } from "../../store/useRefreshState";

const perPage = 2;

function MangaList(props) {

  const [pages, setPages] = useState(1);

  const router = useRouter();

  const [refreshState] = useRefreshState()

  const { categories } = props;
  const { mangas } = props;
  const { mangasCount } = props;

  useEffect(() => {

    const pageNum = mangas.length === 0 ? 1 : Math.ceil(mangasCount / perPage);
    setPages(pageNum);
    
    router.events.on("routeChangeStart", refreshState);

    return () => {
      router.events.off("routeChangeStart", refreshState);

    };
  }, []);


  return (
    <Fragment>
      <Head>
        <title>Manga Srbija | Sve Mange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bgcolor={"background.default"} className="container">
        <SideBar categories={categories} />
        <main className={styles.main}>
          <div className={styles.pageTitle}>
            <h1>Sve Mange Na Jednom Mestu</h1>
          </div>
          <div className={styles.pageDescription}>
            Najpopularnije mange na Balkanu!
          </div>
          <div className={styles.letters}>
            <Letters styles={styles} />
          </div>
          <div>
            <MangaListItems  stItems mangas={mangas} perPage={perPage} />
          </div>
          <div className={styles.pagination}>
            <AppPagination pages={pages} />
          </div>
        </main>
      </Box>
    </Fragment>
  );
}

export async function getStaticProps() {
  try {
    const mangas = await getByLetter(1, perPage);

    const mangasCount = await countMangas();

    const categories = await getCategories();
    return {
      props: {
        categories,
        mangas,
        mangasCount,
      },
    };
  } catch (err) {
    console.log(err);
  }
}

export default MangaList;
