import Head from "next/head";
//styles
import styles from "../../../styles/popular-mangas/Popular.module.css";
//components
//API
import { getCategories } from "../../../api/categories";

import { Fragment, useEffect } from "react";
import { Box } from "@mui/system";
import { useRouter } from "next/router";
import { useRefreshState } from "../../../store/useRefreshState";
import SideBar from "../../../components/layout/SideBar/SideBar";
import UserFavoritesGrid from "../../../components/UserMangas/UserFavoritesGrid";


function UserFavorites(props) {

  const router = useRouter();

  const [refreshState] = useRefreshState();

  const { categories } = props;

  useEffect(() => {
    router.events.on("routeChangeStart", refreshState);

    return () => {
      router.events.off("routeChangeStart", refreshState);
    };
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Manga Srbija | Favoirti Korisnika</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bgcolor={"background.default"} className="container">
        <SideBar categories={categories} />
        <main className={styles.main}>
          <div className={styles.pageTitle}>
            <h1>Vaše omiljene mange</h1>
          </div>
          <div className={styles.pageDescription}>
            Vaša kolekcije omiljenih mangi!
          </div>
          <div style={{minHeight:'100%'}}>
            <UserFavoritesGrid />
          </div>
        </main>
      </Box>
    </Fragment>
  );
}

export async function getStaticProps() {
  try {
    const categories = await getCategories();
    return {
      props: {
        categories,
      },
    };
  } catch (err) {
    console.log(err);
  }
}

export default UserFavorites;
