import Head from "next/head";
//styles
import styles from "../../styles/popular-mangas/Popular.module.css";
//components
//API
import { getCategories } from "../../api/categories";
import { getMostPopular, countMangas } from "../../api/mangas";
import SideBar from "../../components/layout/SideBar/SideBar";
import PopularMangaItems from "../../components/Popular/PopularMangaItems";
import AppPagination from "../../components/UI/AppPagination";
import { Fragment, useEffect, useState } from "react";
import { Box } from "@mui/material";
import { useRefreshState } from "../../store/useRefreshState";
import { useRouter } from "next/router";


const perPage = 2;

function MostPopular(props) {

  const router = useRouter()
  const [pages, setPages] = useState(1);
  const { categories } = props;
  const { mostPopular } = props;
  const { mangasCount } = props;
  const [refreshState] = useRefreshState();


  useEffect(() => {
    const pageNum =
      mostPopular.length === 0 ? 0 : Math.round(mangasCount / perPage);
    setPages(pageNum);

    router.events.on("routeChangeStart", refreshState);

    return () => {
      router.events.off("routeChangeStart", refreshState);
    };
  }, []);

  return (
    <Fragment>
      <Head>
        <title>Manga Srbija | Popluarne Mange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bgcolor={"background.default"} className="container">
        <SideBar categories={categories} />
        <main className={styles.main}>
          <div className={styles.pageTitle}>
            <h1>Popularne Mange</h1>
          </div>
          <div className={styles.pageDescription}>
            Najpopularnije mange na Balkanu!
          </div>
          <div>
            <PopularMangaItems mangas={mostPopular} />
          </div>
          <div className={styles.pagination}>
            <AppPagination pages={pages} />
          </div>
        </main>
      </Box>
    </Fragment>
  );
}

export async function getStaticProps() {
  const mostPopular = await getMostPopular(1, perPage);
  const mangasCount = await countMangas();

  const categories = await getCategories();

  return {
    props: {
      categories,
      mostPopular,
      mangasCount,
    },
  };
}

export default MostPopular;
