import Head from "next/head";
//styles
import styles from "../styles/Home.module.css";
//components
import HotReleases from "../components/HotReleases/HotReleases";
import RecentlyAdded from "../components/RecentlyAdded/RecentlyAdded";
//API
import { getCategories } from "../api/categories";
import { getRecentlyAdded, getTopRated } from "../api/mangas";
import { getHotReleases } from "../api/chapters";
import TopRated from "../components/TopRated/TopRated";
import SideBar from "../components/layout/SideBar/SideBar";
import { Box, Paper } from "@mui/material";
import { Fragment } from "react";

function Home(props) {
  const { hotReleases } = props;
  const { recenltyAdded } = props;
  const { topRated } = props;

  const { categories } = props;

  return (
    <Fragment>
      <Head>
        <title>Manga Srbija | Početna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Paper sx={{backgroundColor:"background.default"}} elevation={6} className="container">
        <SideBar categories={categories} />
        <main className={styles.main}>
          <HotReleases data={hotReleases} />
          <RecentlyAdded data={recenltyAdded} />
          <TopRated data={topRated} />
        </main>
      </Paper>
    </Fragment>
  );
}

export async function getStaticProps() {
  const hots = await getHotReleases();
  const recenlty = await getRecentlyAdded();
  const topRated = await getTopRated();

  const categories = await getCategories();

  return {
    props: {
      hotReleases: hots,
      recenltyAdded: recenlty,
      topRated,
      categories: categories,
    },
  };
}

export default Home;
