export const API_BASE = 'http://localhost:5057'
export const MANGAS = 'mangas'
export const CATEGORIES = 'categories'
export const CHAPTERS = 'chapters'
export const IMAGES_FOLDER = 'http://localhost:5057/images'